---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobserve-secret
  namespace: openobserve
spec:
  encryptedData:
    ZO_ROOT_USER_EMAIL: AgAZPx/CEUuH/CZyc9qWGlwr5+XFW93kJFmbNs8PjO3ua0YZCZG+VtgaVDc076aQbpQnZk4rHH3Uz40KfWq7YRGdF119JHj/8TZEG2kc4fYScJaqzQiKJQZ923v+bWJ87Chlz1jClnsTwQU5RBUvNRG8psI/j62+DSg1p6XTFwHtrx1fXHz6dlaWndsTT0HYah4yiwOR1JaCEigFVpfehbCFpkrvYo0HhTHrxKCPKfggUexYgUe3BbHF4oW9ze5ARmIYvpwjAN7Dr6Q8Ohqzj9Wuzaf2x626VFaEp6X3DrQm16E6oT8H9eYe2JZdPcGtMZ81XZfhoVG04IDKrUABce+rDu4MXQnOk9BHBNLv0+O9UHydQIdj27r+xtap++TFrqUjOSzAY6j96hk18n8PpNwwmW9EIpPwjPdc+ds7R6rrmqZd07aIts3sBv5dxvG0MEtYc/wh78GrPcDd5E5CZfOC0TedHh6WhPmqanmLN0ZzqNGH3wBPne8vkCvLbFLGk8l+/IsjYuI9UhTe+F9Jj2vKzUZNYjREFIjtDyCeabznMcmbNul8j4xnPSfv9DbddL6dwbs2C6akB0cyUkvtk61/86pHRUjMNMO8zy/M9crntMARVMBWb+4HybZxWH3gCEyJXTM5gpzywcUApZff+GMLgjPjFNehxn5iTOv8uV2B/nX8M9Af8d0iN23RVr54tb/Uf0HgDu+GTmo1PoEmtw222pU=
    ZO_ROOT_USER_PASSWORD: AgB/1JoQkieobV4Jb4EH/Z/VQTn4xXgBTCTHW0mr8COA6oDWW4g3MWu/7iF56G2S/tsz2sDWcg+K8NldnseQx5r2n3345+JwQTJE0Kp69d+ukOipD3tM+yE11/f89fYRJg7TY2vo59TXQU/bzNVl7lIPVLoZ72WrkaoiFMwpEL7NG3cQZ3aPF22UCEsivqSCb56uBnj91nmx9GzDmFvHiCLm0r4495GVFkW3ediWXncCB5SGKGcmEqDv6UQ+2/lG/XkwGR8GyuIx6YcnKvI2p1nVhHoleaRXQKvTdSRHa5nkA2CFA3wfM36QwOS+MEX4ioH/DWtCc9IM4chSwuJbqbzNJsugTlw7dSf1+tQK2XElnTvlrlPcr1ntSPrDftFfyI8B1zGM4kTZyYjxQvRIHSOhWyltielv4S0CLSQdGRntIEKlnB+60SH7Azwx6sGA+LdDKpbgWM/uqaW3pBM2SUabSzGrHvVuXy94pWAOYHHtHtiRVAl9Btf/hNeKBbN6VStXPxCs3DPsQbzE1P3JIowWT7ItG3lGWDwVnYl33b+ChFObby4t9NOJWQ41Om7Ed4TXkFsOhJTn8O+bbh8JQL9uk/GABEoPXeW0rju0DzrRj0mP1mkXW4ugRp8wyNizVcXwB/U13TGje032emEygKH+UgABQ3ItsUDyjHNr/0t8knto8V9lLoyCtbWIoVpAzDyHQxyM/FaajDgRsaDh8kOoBOIs
  template:
    metadata:
      name: openobserve-secret
      namespace: openobserve
    type: Opaque
