---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keepout-env
  namespace: keepout
spec:
  encryptedData:
    KEEPOUT_ADMIN_EMAIL: AgA0l1I55hni/YgCpHofUnpNXsj+vrEn68TAFfZi0zskhwyjQ5+pD+iV8RGS1p3SfU34FLGJoKIw05JATICFMVwV7JINXGoPq+B9Zwq0WYoH+Vrj/kn2e4I1Z02NoPZVUhMIIPYAJZZ8ckdzjIQtoyKmsEM4xLDWwlt9cb3vemt7O/vHlpzPIPLABHVWA89/MlPrhWqJuyZcM6rupxCeb7FOy7lRrhi182il3u3vIwFIfNnXWKHugWEOGoy1lb8DrxIqSpKvVa+EfBByz0Vyh7Z/ker1r03OB4LkcHrN7I76rD9ssmxDqtMGVdFZ5d8a5jpoCTRiBGkdSxYZpcPLyN8YgsLoTJq1NaTWbEkaWIwTX+cd0cqP4wsHC9nxOcK8WIOsUkcFjDXalrs9bqKc+zuq9tNmXaUg6qOvN5QwYdX5bseFa3H4kxay06hv6Y1e0XIoQ1wzDH5m22AQlsKYj5Uo9A+OP5sq1Q+xJpJAIypmqxmHA/DcH8EhF4+rJsW3sh8Fqsmu7CNAMt7K+zjWT98/c174NDwsNDDxs6bmb2Sc2Z1tYD5ckEmlvsclDsjqzF/9qmn2J6MMzZ88aEjPoncJe80MfUqyRQQWHdnYNUen0TKouJqqkPJExYR2vVvSFgDfkzQFq/AgjgDquap3kxhvaiH5+y6XeuO8sUJToWCUiLehW7AZ5Qzp0Tq8bSwJm9yLcRDxha5C/FOh1+k+7U1tMtA=
    KEEPOUT_ADMIN_PASSWORD: AgBQPsp44NIriKgrwzwt9uHE2VtHAmkKrJzqd7VtdeKOukdsCPsb3+RkeIh/iHI72l0CRhiXApULndjQgsx9YVmuMaQGe2EG+JSyV3E6/tS25uLwlEnatWc6qt+V94oQQwC+Q+arZoY8xuSSgF5ARkqcIukasizrBuymNsHfRsv9SdeKsdqBTTsXnrlcTvghLuljiYt9z00VMhNgauOtSANs9qZNtNYrr6AndV2zZ8svKb6UgovBy03952MS96TRu4A40rRwPHEwrHC+//wiqLPafeCbjXig9S2AgynmsddOTFY06yHdejyzNF9aqsnhI/kPjlbi53PnoOeqrR6HQ5Y6geTclrf2Mm0DhewMdZi8kwtfd4pjtBkkE5VBDGoNx3U56JKA+MtTKCL9D545ZV3ReiXDOZxmtJC6jCDx8BLKaTcOqkk0wZBHiv/zotckx5DrLXi4/WPomY6eE/Epx1KM++Vy/C7sVu5pKM+ocg2aWwTUKCfhNhLFB5Xl5B3OdYjgvgvZWZDrYkoBbWz5ZJalU48ozQqmyOfmpiWMj++CleUloucIbZZlQ1z1XZQuHbPKo4e6GyylnxoYECGM3S23ryLPVnpOKeTtBghB+Mh8X4tnaNQb1HPSQWoA3sgOxhax6UVfLJErLW/dhgaGzHmuAbvT9a8rbBa6laJ2zQ4xYdAT4mW+jNBAOvFY0dtNg24rmhyD9InSYPi8oz/eqdVlNGrD
    KEEPOUT_SESSION_SECRET: AgA7kLsab72cp48030bVpRuNHBx7BCQ2RMqxgVnbD2yK+8F3TuI+WzLEw87lyIqUOesNjmtF5/p1E9FxX0RZBcpNl53jM+/EGgKs0o56SPmCCPn1qyi2bq1sSEJxdwbNC2b43OzD9QFseYuvXkF0/56N1ppx5JSm5qIBWDjzNei5m0hpT4KWHSQThL6NoYWP85UiY1+oxdrtFNl02qRPxsLwCqvpV3d6TMvGRwZZzkIVx18Xp6+aLk5xXH7Yxq8nNZ2nlIO9aOEBavPX0YlKyrNEKw67DcImm1vq0OmFSF8pPdSYZKOn91stc0ju1gvIdpWjoh+Qj9IJcf80KE19RM4tjtE4I+UkOWjJxnubIt4ZHIjcnQA+HrxvNHaphiqkWlLedDgQ0TV8lwMYYFQXqBo9gFun7oF4YAAf29e2Ukni304MPge7rlgbJgfhlpXNoskskserOjoeu1Nxra+iyA2vAXLvrUJY0fJy2ypMpbjyamBmLgjsKEbEhiqonUhQSoATK2iQ/ZZiI8Gahnd49+hXSPRmiXuJut2eaS18rsgc/sCvVzxxgDN0A/5/S8R8qcomXA9XuwIeq2I2oqcRrZQzrTh2UxMwjJIsR0fVg06TaII6anG6i2F9muSOQgRh5apMy3epiitZIs5t2aZVACP67Xo1aFzpN+PoYA17wek5cMjAB8YXETCpqMFKYLWA4v19r5XB1y5Jd3Xh5m13c0zfgpfpKKDxxDcPkhGWJtsv7E2SV0Cx6iS9+0ArCb9fnNJ05u0J2WrhX6iWwlNl8Hp0
  template:
    metadata:
      name: keepout-env
      namespace: keepout
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  namespace: keepout
spec:
  encryptedData:
    .dockerconfigjson: AgBYnHkwXF26laoSzIp6Ab02FivE/ZnQKBZkrg8Axu+SYZBS+/G4RlrnY2IEbOANR9wido14SqQBuBo+1ZQPG+/lzyLNM1+vdtsPug7UOlD2w88y0YKxr11gfhcOGpabHBer8gixTZNszoX++vEsUxWDr5sw6OLw/TZlFUfBOINSwBj0hrbDib2Lq/lbrC8P9JU1N5RJlLbb+Pss4lrlqsCmDbaNmNkbnxu9VXKMCUszsLkQmR9EpZJyz/mdQESZMpjzkKnzIjzXPnvB4i0g/C3smiZLRSYnltTTTAHeY89QLZk7tNmvzRnBiw3W/f644BleVwGenareqrvwjansSNXwGUhle9e+1cqDSwzYV4wbqIdvB13NWDXIy11V/8c4jkuSoWFJh+FQV0JDe8RCanX5MhpkWkWV6Ok2vXNLDmsUrtbAZR3gslq0+5z87f7WTkxcaCA1Wm6s2jYDYkrS05NKsKfDAJO5CsRBIltSJg8iwh5Mf9j/q0VCp1NxaCtW2kiA08WHfFmmcLlf+gQj7GjKT9XHF34DfeydEFseJLwVTmtTMcgQ47DDoBoYQN5qOYFvWimiE1l5Xm2R/UfDMsqEiS5/eidZJkcpiKA7A0y80CIwoZ5oc/a2p8kolmY2bFrezVXk8F1rYOok11e+jujB61MiotnaPoo0T4mKVrm3HJabDsFQJb8uQ51XTavUQ6wcugr6KNKzOmz9fIuAbM7JB0Ut51RkRSMLo0p++9qg42n0FPY8bFtpG+iJd7i1pQbjItl4ZhNXvOtViCKeocadcjXpVouyGXZs105kQdrQbp/HI5dhWj46utoOwSdEn1YKpYoOaY6hfA==
  template:
    metadata:
      name: gitea-registry
      namespace: keepout
    type: kubernetes.io/dockerconfigjson
