---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit-secret
  namespace: fluentbit
spec:
  encryptedData:
    O2_TOKEN: AgC1Ls5yflTA/pSSmoTm6ZFI/lL1vHjneqEJ5ILOnTAScjJs8CZDz5AjmmFO6tK1w1LpV7rhg1bQEqn7a+S926JBR5XdGivQFPOvwnHYJmnkkeqfBh+L/t7uNNSTAr+iC4jlyy6qdwHkCDOMLQ8Ell0U5gF8X7GSAM9BkAHEheEZXyJ7a1cGCaEhi2k62dj2Rm7LvwQwlxDaVqXHmxUV5kyIPHErMopRL2G3ijlsn410gUZoK5v/TAXmllO4DctST8aAcbsZv+7RPRQFW5L12ZuLch9CYXnwBs540Ov4WhVXFDcLQkoUqyE0h5/QcOpsEU3Y8lcnf9bG5QChwaXFlwH/AVDKbWxhaOUZDRvaIWGWcT0SUOYjIHiuFwkzUXgfaf7UIzYMOo84+hjAgr+aWJndW+NlPzoUCZs1jy6kYYGih9ll5QxQAgJIIdVP4SSZ/qU/5SECgvCJnYHpvuTe3J1B6Ph/Z3+7hpEpcKQn7C5tq/tq44/9YuOmZONOHhKUL4XidVDWrC/TTA/7V4JY9kpqZ3njAn56jcsjt/RFzZq3HNL26YBhAdV48y8wVZ3mr0qLtqH4YRQ0/OKLWz28i6yKlAwYNnL7pulcONIubHy6O3gB7+k+bOjQgsocl84T91cYZGrSUXhtc1hBwN0ihwNmAa98Xz8PiVg8SGI/V4jP0uJx6tk9RKDBMM0QatEnmXzgWJt2hBriYCcfxnO6MoNLijR/eJl4EJ0DGFulDysssAxfWp5pxDnQ/c5FWtkKexOCjUilTfmSQz9c7gw=
  template:
    metadata:
      name: fluentbit-secret
      namespace: fluentbit
    type: Opaque
