---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit-secret
  namespace: fluentbit
spec:
  encryptedData:
    O2_PASSWD: AgATx0lS5Szj0KMR6eOu/tUHvM1qcvHEm2koAjvGjqWdnpzGwozqdQfZFMeDPMsfENdRDr/6FfvOJm9KEdWyfnigEA9n/OqrED8cvgqp7W7qtNLm5rF9C+hfJcJG0HB2TxpQmQumlJs1eNQFKu1nGA/hln/Ko1N7CRlkGkjLP8MQI3YDh63njyMkff3Mwl6IF1cLEb/7i5hMBs96fSNnJLfoq/aOoEst+somLAYHzbaxMmWOI7tctga6UrCsp5KO6p8FRR8gtct0A29ECkVlkUuFu1d4gqPr9uSFEzdbGDosOEKN7CdBvZMmnak9YD7nRGrG5S7K11Hw7BbVi1zS+vVOfeKccb+toHjhd3Hxuj5NgNDSEe7Ywqn4VT/RLp+p5pT1lOgJ7LzCh23bj/cKMdWA+j3yW/MCytbWtCS/abKlMdN+MaWY46pYmOuxISqBXM4OFwWCuoGIzzqGJ/wOvtcOCREyJZKK5cz1se8SmfXFywevtRgWXPRrJtGBW4NKYwZhpy1qaB42WJg/lCoCPQgEVpRbyPE/SbNnfC/iQvNYZoLFZYIX9no0/WKEwa8f47MFyWdRqLC9hOUrw0b3q+5nTEvN8123zS4I0q+4Sz8NmZgR723AR1X0eIiQYJXCOs8bXreVbsLHcGGuiylzflaHQI8EZsJmRjYDtr0Ro7elt5NIPXVXK1xYDP5CyVktsgN+7PuSETlP7ZK8A+QJ96p8TcMw7jd1CjKL6ubOGH2PvrZpoDXMWPVs1MNkVuZa1egWjLXXDFcwWkvMw74=
    O2_USER: AgCBZ70ZUjnLIq3OImertNOvxvYS8JEh1hDCcLcI3c6ZkhcSCdvq0IQWecwTw1ZT3lY5pyCCOgWPzcASOw83YYm9PWCr0EJKv8vB2XtxkWmM5jmoJz1pK3HjCHGygE4cJwJo/3WsGzjWaEus8AHyOB0TB0ICcYeW3kdHgn3iO172w4sTl5PaG4SFRKfbUEFbe3aX039/B1xaempNbePgCtrP1CTVTJYIofZJpfJpq5DEFVpGM/XmjEet1PEXgYxNGq8ARA07QeDExM4Ze+yYzWL5AM7l9yswsYQ8efHCFPnAWALFvrZvwDsl2Do1UTksdqGgxvjSQlGGP68LtzjOYi19tePWlVNXiBz/n6pKGiVpyf1+4fQk/Hr6dArGda7gsR8QqDdQK5w8SDRgcizFHr6YFgxpo2JWe8/xRu9JgaSSDP2P0FZNvE3Jd05ofxyPN+6Vb9n0hY644tW5p2hu8k24BH9Hl1JCeYfFWu9WDSrhGkiFauAbU7eMZ7YSXTzR3rvS8FpZQTaxXhloID+ImBAMscebtLo4rxqwZ67YWDhJh6ftVk6a3M4kCaQ7xx4vDyI0l6D2p9Ch0OePqpNfa/Uvbc6CMDyDQs7tpm3L942FWmuuxLoHFKt+w6jQ5XXbdiGz7wO/t86l6wJcTmiBvVU2NA/LhabRohLMi1SIN8lmxttpxvDhvZdT3Cz/isww0QBWAD0uIwOfWLUd6pXACsLV7uw=
  template:
    metadata:
      name: fluentbit-secret
      namespace: fluentbit
    type: Opaque
