apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.rustfs.com
    chart: rustfs
    targetRevision: 0.8.0
    helm:
      values: |
        replicaCount: 1
        mode:
          standalone:
            enabled: true
          distributed:
            enabled: false
        secret:
          existingSecret: rustfs
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
          hosts:
            - host: s3.jmly.me
              paths:
                - path: /
                  pathType: Prefix
        config:
          rustfs:
            log_level: "warn"
            region: "rustfs"
            obs_log_directory: ""
            log_rotation:
              size: 100
              time: day
              keep_files: 30

  destination:
    server: https://kubernetes.default.svc
    namespace: rustfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true