apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 39.0.7
    helm:
      values: |
        image:
          tag: 3.6.13
        global:
          sendAnonymousUsage: true
        logs:
          access:
            enabled: true
            format: "json"
            timezone: "Asia/Seoul"
        ports:
          traefik:
            expose:
              default: true
            exposedPort: 29000
          metrics:
            expose:
              default: true
            exposedPort: 29001
        persistence:
          enabled: true
        certificatesResolvers: 
          letsencrypt:
            acme:
              caServer: https://acme-staging-v02.api.letsencrypt.org/directory
              email: juuuwon2@gmail.com
              storage: /data/acme.json
              httpChallenge:
                entryPoint: web
        api:
          dashboard: true
          insecure: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true