---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs
  namespace: rustfs
spec:
  encryptedData:
    access_key: AgAl2IKRoeF+0pGNqkFBh38lsjCw1suHhh7jEnHnNgHCmizcwW6x2SuxdGTrDe+jaexatVVoaR9MibFd5S50KQxOsjHxiX4ZzpAhTkmIBcqyxYIuY7ygzkdYYsJ7DEUsemq6RCUV7ISWJzJkC2u+bEpy5/hNwbf1coFq6rargxoi7v5r3ZFDQT/iMtTtJVpBDzleC9w7Kib2Ibq6f3s+d5vZq7EzY8CrDnkdL80jdKiq+YFHPyQR3nUSeNxK2BNyJQruN8Io+pkLAyUe/nhGLETAwWp36b3Klvg8F2aHLwOgIFslqfyYDNfOr0Kzk9RtfT5/dEnAphBfMeFYmhiClsmaoQmC6JxeX9ARWfrei+UKcD2VrwliEMkJ9RI4/8zkXR2SArJkTZBYGa/EBZt5dr1tNyfGCFlGCLB+rzuCTZQs6sAYnhZBbV1sCnfvdZtejh6fwbGsiFDCoyFNvcZRYJwUa+3c9Uv7N0/bjbjFPYa/nMXirciz2Pu1cp2tKuqionF7dPL32Sk1WyRUFfUC4U81NFf5SlLpA5lMTNZpkWkwOs3u0qsP3+NgGtOqGTBrxndpGiYAzUjuodj39rFWWh9XJmDdBKw1EOKn+3ZwSE5BhGESpkYVWWNiGfTzC5JCOV9H+4AzfSReljL0KmTL/1sB4JcQTvl4RY4D0/lqQV/gLqp+cDlHEGDclnCmJ1H0ZbUe3XKs2mah+Q==
    secret_key: AgBVPPm5xkLFBWa8BwlPQev/Rayp15hiVgbZUMlPKjBi1ozf2zEPcCFdOLwgiTyPg0Xhilx5BpCbXaYS/a/egGNwwahxqkBcl804NkhIO6ao53v09UqqkfES8NbozZS48Icr3tdSilKg4djqkIPzGcJXETDmla9U9gZXGqSjZx2Z6Wk+S2Vj671spawWvo8JFgio0KssexqYaUbAoMrDYhwE23iI8HyZPKXbJ+VwF5DTVMI4ujawLRFFRuy7LyrvIKGW1u0FCGiPlOnmy+vd9DsUnSZy87Rp94oaJhW4P8ddfZDfBfohRg4YxbsZJrm4JtgKmvRCZuEK7kshH/VfjXVXy/Yd7XaTzaVRlU3l+S1AblgI9dbgHZ6Nicc1jsl9LtQBI5bnZ/85iAXqDFftjjLiGIglcSBiWX+z7H8QktVk5ERvGRfv3SAsKXzk9lX+LDKlTPWy35Nscgdq/sYXdqiOzxFVmXBNf+R83KXIGCLnNK4RVdPvzSyJHcjuWcLO4OoIlOTps1N7XN9mg9/Y3iaqmibcDjY8sWfKFJvSPW09FG0tTpOzz7AzAU4eSBe2fxHkWPSlLoUCmUmrctFM8Q/em+tUVFZxdGDXuQLmlOV5pA793KX0B0Kx07Y7+or7bYbFbjn/pvc9nxNIL2gq0K24rYhvGsVd8f90Ihu31IVAHOeuoGh64lHbOiRE37IDaWc2E7xM1t2hUg24RDA12Q==
  template:
    metadata:
      name: rustfs
      namespace: rustfs
    type: Opaque
