---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCGaGmZ1rHuSsF91erSFrdDuSzaSvEYYT5qUXuUYmBHmCF6GqcsTbxvqAJolmHlu0BZjjIOSMpgtfnYkIxF5iuDD/fxxVOrN0I5vr7PM+VSS70hk1Ysh7tTJJUgZW9gkUhBtCJCCnUM/F7xTUtQh98uJ2Uc8CkgxAWF2LQaQgD6pmL0/f+EDBs6MyWbv9mQZ+ML0R5+PAGe4DwDdOP93TDnH3cvFw/Hpmydda58LDZcbOWaFFgJ46zZ2BV1AaNmAzXp3CP52mcEUMyWDHyHM+dvYj4yJMmH/MYbVdTtKRMDaeSuDQU0uZc7jnlTPcphzo2IYMkw6WCIHpEiCnwKVakRssDx9pMCua0TBv5dNEDcYCVY2Kd6OOCJ6jpKzBvNEQqtIBwhVWlR0OGDrOhXdeyKtkNU0JD/bQKfvuMFiGyyDR5rO7oIQcwi5arbZCFwwPC2AoUI/yfFoUzwI7U4hv5IKMyzE3Fr4RpRyNLRG4GVPL7in4clgTy+ZHQHwbB4n989y9acn3uPAs5HfrGifRq+SQneQCvHvb7gRTyfqxvx6CGElJU3v2xL4fcrvb7NfT1yjfzIivNINMIX4wxHa1Fg7f7VDsaz7gZDBtfwmYuxxeQIJn0obVL2eqcVGtfHzSXuVQefouESI8UQnEOVXUb+3m0ey1R2lSbPqaUaebMe91M+2N++ECtiD24I5oRyR20h/HK6diO40A==
    RUSTFS_SECRET_KEY: AgAyfFsxiqN42SwszpM5EH8Je5o+C0cdTV3UttehcvS3YOCSkjq8vk4uSh09mIc557Of1aTswjeugfh6jOOySK8cRW7i3VyU+wvWKLFBHt7PHDI4yQY7xw5W9sr822zoOuLdwsyDx3MGwOkMt2LZ18qr6vuGDPmyj3AyHIr4c7Up7gJVb3+w+t/DKLZkZ8SW1CJA4rrZzckdGGzzUYAZmIN8zGydvcBMfm2t0h5SgY3N55gx8trxH/MAIXYIWHEFVBJf08uI/LrmQjLLNwxXtW4s+njjp8w70pGztvdPfRSfN7LeuSxKjMcXvVnPs2NOF1vee29v6GU3EyPMgIUAHmK9dBSLDwf7hGxk+K/V9Iru3lY8+jRkehznBF7dYVUPevse3zsLDXaWLCOQ0zcNlnVNXwePQaW77FMjNl3Wlt9rwIUa3w1G3eDfUTsg7abcEerj0oZDlz2np8gTNK2HdIAKtAwMMOKv1+5h0u/K9JRwTK0zJZNd94h8DmmnmfLTU3E2JQuEdw3+FsDm+msmHYcXQO54XhVDhV1CVGZTzdinB2NoXLmkERIeamXLb5PpBMo6HhYiLpvHZXGkrZm+PsJ6pFWAtMwto1t+om6a3vNg+Vugdm99uJxU1ch5tYQLmEtah21JZW5hY1FzStkg+GC9dvlCyVus35WOsGamPV4aU8PBskUy5W4/BukpTxxkYNXx7H4HNpe6fj1evLD5iwdBZxJt
  template:
    metadata:
      name: rustfs
      namespace: rustfs
    type: Opaque
