---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs
  namespace: rustfs
spec:
  encryptedData:
    access_key: AgAc/2g/O2id3FJ5G2kWg83mHND2NMFIRMJOpNq8YtMRzrIGD6X7drqktFAx+dzRkNTRIz+EeGUnNM/Bk9IYYIOh3DI2hnSwt2G0Eb6/jEmAHCcYJix0jvVI/8q+mX9Y5dxWXETfSgvEX6SbxlkSPWmFWIK9TnZG4ty/EOpB8Rbl5ckQZUzJbvouag4SOAKRuQ83EomluQRPsAShnfiipJML4JA9HrE+8Xxv/gt7JYZruTBxxXU9Wv8daRaWpCp7Wj93GIO0vmxUrhrx093hhd0tMfuEzy5LjGiQc+cBRJziTVgrqJ5mz1lkepTtCgLM/pGpDYUxlZmKL4VjpqUafh/DdHg0LXpPy7xbny2ZJWqYZGCjc5hoNEI9Qnj+KysSQDOuSuXEKs1P5tZLittICsCdI8fwhgrhxJfo1sRDIDMEtFGjBs97QSJ9ufgcYsMzlthQSe5ZqPEq7yQA4r3i+7BDwRLvZ5y+OGrWwI8Nzxd1PPTwgtawZ2BOKBdH4bqjDR6nLoGHqYgZp/ytNvVwHM3EJvLUys6If9jJwVQ0xLfYzwkV+HmnRpcWNdm91Y3NLFhKRgX07Cey1JCxJj11eS0GqiNOfFz2Kuy8+Nhj8qE6a2MoJvDYDfgaow00XohemN1mPgE2U/0k77UyTwAh6Go3OQuDt/8jLbSxmuDM9061M9mF7klkQ3bArHxF+7N/BCLa4joWjnXm8A==
    secret_key: AgBmPMBQCKygNbMKb031q1TCzukJfrnvC5YfHzYB5UGFjiTSS+5eRCuLLDMi3tQKXoyt/BcReuS2WwjROVpRuCsfwXXMqRAvjuU4FyfvNJ9i+e5tyMjFvGKwrZ3km+u/hjf+WNnpBSw92O/BG7DklNYI13wVW5leJonfY4yMV0PEP6Z0Mi+DMXi1exxOyRUGSVD4gqcnc4Fq4C5rTTKnvnuMrReueNRIWMM96qrL+zTlTTpWvQ51vD/lwj1JlRhdoiCChiVgOLcMsEYjNWOa0pP9fMQuzMr1TTeS62vLzC6pt8pqKNWrsRqyXiQ29NPizItcTo5pR8/+ErMqxjBd4iT+VtN0/GSAVo690JQn8aDii9HFNhyXoUWvmN2GI1v2n6g8bfbdVNDVEDkkylnr09XbYeN1ktVboPA7VjxSPIOYs0lkennu/W6ildm/oGidrxmknRFU8sr1+jRb6jAy4t8ukLHUwlwWtPgcxc+j72KmYnZ8j3Co2XtQ9d/vzKc0WmGSXWqwf4hjiivCirbuuZsDESBY+gkSyKel2mk2gCukXExqB4Qzg/ttzwU5hsy5Sgz9/Lj49bD8MOGHYsDFfWQIUh+zOvHfGFyVCrYpefTrLjW+H0oZafzbuozolIoLQa7kiISAXBtUnaDciyJgmKf5dLnepgQET7MgJAJFRUfID4jYE5pUBNXaR/rxno6q1FVp1WRiZcayiZ/vxT9HPw==
  template:
    metadata:
      name: rustfs
      namespace: rustfs
    type: Opaque
