---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-registry
  namespace: keepout
spec:
  encryptedData:
    .dockerconfigjson: AgC7BrK2HvD7bvVWM9awkZezj1O7CsYMlGXrMOwRp4qjhffGiqdkTevZ5h3QCqOgFPb0JxrLUu5zVtnjiIjJ9IORw0oK2J9KSgongR6ILG+ooEC5wQSvWem86fi6Q2l/6X9iRORVID80vO3hRUOgCYkIOQe7QcGoeLXxSRxhUSe522LuRJPeW9tMw7rMTs9oLvUpfVgHotG7THe5bzO2ABZwPZ17N7d2o8EuNBS1NliXWG6rIDc96DlcA7bR6Fl3HMab7ZkjVNEukKqgPIjEzRIdHGVu5HFh5gnsnJSozK1RVd+PnGLX6GbipeeXJns9v+l5W2H7KSQaVNiumgivXPl58EtDP5xYRilDUkY2kVVsJKSeTUCW5oXgZXuRC/XOs3pj0QdVRhse2wR7JJ52xcYtbBusTEL7HCML4rJSY9ukMGHj/uz/kzh/txOpt8ZZfbLzTf2hNm3ePMvxhN60LGSHz9ugigOefhL4QRB1llB4w52PNRlmc2BqnveXTmDZKyz+Alu3oWTbwefdoynav4uvTrXlt6Wjk27DBVEZRITxAtKFHthQQ3yPhHbKYc5cOZdgnY41waxyQawCYggyxzYomcofUnYHje7Td9dIY5NhPIIhXqKb1ZAHX8ODRJqyqjTapF7wShEIAIiHfW/hOD6FMHsnQMTgcJCK0O6STcrrGOiA44r5rCAmguzUj3kpyQI0ym72t4qU8v4xyXfo/zCT97H/1RFPwUAz/UMf8K0fiu7C11ZDLCFSC3Tm+MWJq0VxIwLlPgiX+Ex4YLkWlXY41Dm/CEM+g9HjGDh/O68KcjJcKFhGGgz2Hxx+Tco6ta385Br6T0o9kA==
  template:
    metadata:
      name: gitea-registry
      namespace: keepout
    type: kubernetes.io/dockerconfigjson
