---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgArMb7/a91+SaN43VgrDDTozlolFihAyPRwdTXFj3yXKvFIqKYJhPHFJtCx2DZFnIziwSLlo3xZMEFxusqcMBqjMq0d/HbXyKXWij/ZfoXJR8A/9Zd54YOKF9RxUfJqVWSN5dcmYZTo0zixanC8fUboPUT5AR9kNufJckTDUXsiYHDuyMEsTs4bii7MWOt7444LsZADtlGrfpeLv1UIFuT0Vhb4ixjTjDjhaP/TATgIJQSCzCUmWytv0d/YxnLxISoMccGGp1Qnux36ph9KD965x2+DPfNCrfW/aRJ/Qm/KUnfO7ZaQuc7yIgbdoLyJ/3SHC2bD63eZhXocJc2eUvxlf6VL2u1s20YBgCCRqlZ1CJHqrVQSVryvaaZUezUTdVcz61hkAZ+eDkzF9N8VksUsKrvdlbBmHhvnso1rJOIWppbhIBov1xtKA9ta9AnyRx7YSW1Y2BkKp5OBxt1SN0R92LdY8jWNUkxubex2PJObr6ZWO9ALnioiglVgCN1o+VpVuqqHu7MeO2sFHctJW5394znV9+XDaC4jk9OJgxzvkj2GZeaA8dlT5Dvu+tcbKKfATaGy309NgjNaJ/U8DhERJ9Ztwn9HcrvLOdmpRmZN5/q4RiV5qdjy1g7LCs+G8rVyR3YJEDHEjKd0KXXffjgBRJsUXVaPefkc1HhLS7g4DTA1N6N6nv2vsgL5ew1FaJ3OpI6HdnNGqqqkHA==
    admin-user: AgBz7QLvufhU9cj+qpMycaZLwhVc2C1kRwK7mV+lbLYT2iXXdx9yR33KEV2Duhh2mJNey1fHMQAWmgVy6+IJc/qJeHOLk3PYNhRZkh8Y1KkSKAo2E2/VTijdozchRb80RZP0g6JqtJMhVpfi2aeYhR6lUCT4fFJWya571YE/sYbxggRZkzcbAIPvfJ6FDqDinivJvmtI1CSuHx+DmBq/O3eeEYeiX8xQ1JUPXD1HAf+wnA4b6yqv2rm0N3tw7OIdFOOkeRKfTbAJ/KTvmsbgoj9Y9xCSylo+K4Z4nFrvz6RKoaCE8+5p9wPghXTypT3r4ykE2RqaEnbQVmUIXU9Obl5lLTkt87gQ4Fufa7p+3kx5vQV9PXaDYRRZiHoNImJX+myPRX8fRN9gQz33F0DzTtv2x2AOPl9DGfkehM7yb6adEfE0sCO5lD5xrH2WKWPG/i/TlwtWdAQvFvADTW4IxkUvgCsjcwSm/WcLha9ggBgaPQVhrWn7LYcdqtkgcklXjEO3NvRQJ6ngJTvUZZ246Iy6BGj3XTtlivTKqmLhea6BkW7Dz/LdmqnSINL43WXZiY5E8sLeUPCF3bwVPafKLSVCWsDwkFJH6dWhZmk0moLMAOkveQVHE1eP4kx8oZ/5mcXYCGWqDEDMCPRaPfdz07YeRCp9uIP8/gpW6oQnyobqBorTpJWk36R9o0bEeiwnolWTa/HSYuRPWg==
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
