---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBzRRVxnDmuC1f054dKA/qfZZ3GEs/KLAvrUDtQ38/WO0rqRDNl0HlYLeru5G7QjC03HK5rwwHR1hvAfHJKVJo7r61PylVvAahIUoAUm6IAvtOSKe2hm85mdsySqFBB+/LuVHlekGTR1FdHPRHd4OKMCkkXNX9Xwt8lAT1spZ5782zAPSHJ/Y5BbpnWTJLZkGa9zWuZK3jJ5XNBcxc4GMdcV2ZlWwy0SG59CAc6qV6uok7fgmuz+h0ynZ9m6VYAozI04Nslka9/kn3aZ8EM8gvO6JTVpZmpn+ty6h2mziMg+xDtKDkxxStkTP5kUQs9vAiRaNVU0cRFdFPt6/2c8JRpfSi1TrReH8bdtsFNRFM7p/iPoauxk6Z1D2RcSPB0tXXVKGiiHq+c92AY21JqRoF2XJccKwYlIFgkXE7M968EchKfGOpa9FoPMg2f8EleRwyP4u1HzdTiU3zbWCcjEkXAdO57UcG0bUYCnRC9HjkcDNPJ2SV/howr8LFt8iOrHkm2rxPB8DUwb00UQ7a5TwdZo1m8o5LR0wbmipn0gsiBi37WB0v4ppWbgFHQbOSek0wlrDdyhlSbjKGiOqawbr9jBMUz2XwQiGKjkrldSkbq23Irj+/RyQq1nT7+bBudzsoFByGXArFfPh6PhvUFUbbZaX4EUHD1ExTDh9MDUS7Ykruwisn/5EjO0l4zu6UHzB4HUG4pB9yu4S8yU0eiTA==
    admin-user: AgAkdsOBZHFeKbYi1xShr8LJipGoKDsjp4wR0kIMyKAGtK9FCm4WxLZXFkFPrVvkH8ahxv7XYE9wig3z4Au42a922Uq1nFGx5afp9SnVxAYSnds0EIQiIvuzu6skQnuRRRx8FIVrvW+55w71/sUu4PK3dZ7mJyoCNJt7p58B8J2x1E6o8HX9cds7e5QM/dsKtMRoDiQAy45RCWe4sJJYyZIyj7qCICGsV5K0K6lNG0AIzZLAvSRlZ8vqfG9yFePUS1wCoWt7aO09Mfj4MtodsCsouQaiGZjH1541LIljLfOpHX2U2xin7/EV0xRMqXnOVtgITWGesshs7Htt09IWz7k6rN/jc1BRFw7eqvj3ygHcJiYWoUNXjWbnxDeMGUhK418Hd0Sl2M2ZV4R+jBTMtR7wdjZuGYunmLZdVoY6XTU6oZJSimdQpqqGcNDSfg22csMjF3UNyvkdNXrfIsiochsHic0S2MZ4sC6VE8CeickR5zfWKp5E/BJJLfkUH90I3wG3nxjpBFqr4htW1vyu2COH4zEAo0IsFLGlwQKyDY3FSgbni6B6YVvotnR/M4eeG+VL/z2EWV023mnLQDPtTle/AiAEnhaaRaNAaPa8Ls1MhMf0Ygb7mkNrmwrLaUphKjQsaxZm1JUSpIPSHzOOmDUnP9ezB4GMyUIuvT3RcsfL3Xak3H28la0y3OGv7wCZJZirXvM2zYYW8A==
  template:
    metadata:
      name: kube-prometheus-stack
      namespace: monitoring
    type: Opaque
