---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB4eP0r02O258Hyg3skdUGin9TN1WURJ1HQE9dajy1tv8aQo1mVMC+3YJu1jP9OG5Ed4HDzTy3ges7zCo2q7tByeW8wKL2AbEfwotLmXDa0UGiBhT+XvVyh+DAZyyv7Llk+T75aeA80k+dOZQLWCGNuP/1OiM53IyO9z9mbVkoLn3ZbN8dVrZryqLiLYArHGpB4m2pR8LjP1AlLyDqDqXIbfoV7MrEzs5Hpt+mvKAA4GeArc0hJsLOcfJNZc5A/ymnn6t5s8N2mnn+Ca7ZTdwl1NAvwPus+xRJZNCT5FXthjRvBQGE75HT9RN3qTsVuazjZacUfzb4LcQJ6Kx2Hufdu2TpaItg8wfqf2XdFR7APOk1dtNKF8pst4T+GS/tl3WL1L3ZW5IS0KJE0Pp2BCYtX2K2/+6SuFsiIFe6/XUrSXHxv7+9pbMhUUHD1CDEACQsJrOxNRYtJan6YoHgHlKvV5yj9Vh2ma3pYuTuCUnWj/0rPPuP4m+7DmeEPtzR3Hh0wFcOK3na59flWQSrxPTLmhkcGjmkxzBu/o53gcGNIJxLJnKgZ8nhmbQmO3dPRyeygu8Oz2dzUasOGJe+Whh1qfj1Do+3PHRHwqW2H8f5hsDLrAs4/KxuJdqaNwkvA66e9do9bfd7DacxC08m4b769iN79rhzUMAWj1dhyj60Stle17sh31JUDh3Oq12Xz+/VK5/FbhBdIQ/F+Qw==
    admin-user: AgBopfz0/Sv6QcVUremj8PulB9qmKNrNkpU5vx2zLrhNohuhRp6rNCTZLA1xaVfsjoWSuVaTIi5letJCxO4lGhDQIDfiLONlWgm773Vz6jnAMTbC8AfEYlp/FSW2zQJCvmhoYD9l9ghhh331ZLtkmHZUDs8mG8THyyrLenOm9ma9qXoMzNSePoHevs+JJz2PW43ZmouQ5KkIRVKj1ifhFR6VY7y+NqiuuKD3jKso+L6I9I7G1tdwc9Ky6aw/7WRkVjY2aU7EdqWPCszVfaDAIgO4RuTI2HjWsM9qWl94yl/I9RTfvZDFlhklmNr9bmxSete3kTl8S246HcODbz7/vOj08n5c6xbp7goUF3bBzlXREEm4Tvt1wpxfLPTBxOX8OtgTJtizkDZA3vEtWykR/3Je9/22FH3RqBjPcZX/uhk5k1zG1tomY54W6MIje94y2mv6TMc1GzintBzxFEAvDumW9YS5vP5xTIrvcUyKJQP03PiXwSLuyVfkYLIjjSTxSFiUlEG5sVaez5mP4K46DT85YPwguo1Zxl9BVhp+8+4/X6j2XPkYZCN6pjQ8om0t2qOZAeZkrQLTyl7QeilyOdM+SKmLWJ41gOKMw0xTbExyy0XH8aB1RLsH2E0ZL14/KGQK30ZeCr5xIs27H+0mBF7ZEc9hQD7ThzQotfs2SL93zo8mmA98tfDFd+vK5qSJxF+N33akGgiKsA==
  template:
    metadata:
      name: kube-prometheus-stack-secrets
      namespace: monitoring
    type: Opaque
