---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: memos
  namespace: memos
spec:
  encryptedData:
    MEMOS_DATA: AgBiGSdvpUjrwmeW84Md1B3PRqSCjCOrNWCjjxfk55aPZWvEJs5g20tpqNEn3wtgOXmyyrMpBbh4EuPw6uRwON4jN65Km/vVN6RE7k0rsULlACgtscW1P4aeRIZD+YYTQlEAAsMRCMXxOMSsPcWCWmM7yS/FCxayVDlEBwvYD2iwUYQ2izqjoen4Y6nYkc4ammvZ1wwi35w+leNQdLhGDAE+LyZKOI07e8s8+v8QEi0Wii/VgRqD07r2743oUQYj9On4yG3yf4dDoue4G7JORLaRP/GSA9uPoJPjoCXmn29dpavozk8l1cJdnAFMBjoNXQ3kphqu3sP39D740WYH+VmuJhpJ/rbkhai8W5SmOtuejC8eD5+06NVhraXk9e7XRpTqtNRexw4OYyGYYs2h8l0u0/MDzfmhFYYioE1K0oQwroR/es6wodUidPofzvEBg+Vh2kyg9L5Xe3mU6dNvOSRLmvrNUws0UEJEl1KgdbIIwr2ZuijpUImzABDhhASvlqHKwEsDvWhgwio2ep+fXzmwhBa1jTR/fWz+uirnpO97sxHMzKrE1I/vFaV/MXd6cTRabSaj0b/03D19wDbjcw5SUP0ekr+zlnCdF0sp1wKIEK5aoRMB1KvGHjFcv5ArjuA0k51ea7PGhUAztY1wdrg6Dve+FDIpqwKcNfRmCMpocaXjGsarEsTi7Hh0z6WHd0nKuPvIy7c1BnkgsqeDgg==
    MEMOS_DRIVER: AgAzk+6lXezNhMq+qBQNyK+/MtvAnXDna2W89GUeSiJ1bKG29LmcA51pUJQ90vmFrxIIWxymYRa0Vl2mm1iSuSkpks16WWsFT50MA1/2gx3nS2Zm7OdS5eohzwIAzFQba1p5HPF8PNJBwGKY1fteaG3V9AvpdvrkKC9fsYjkbJ4+C8lqNOVnLpWm2xw8m33Yh1o5c4lXp4G5E7blyGuNqQ/C5wcbC8Tkslwnz4tHSTPnOy4BEAT9W3+KqORqoaM3HYkRnBsoT8kC2mebs1b4jq78dM8KEsIuOVvGmGuKu5KSSBrt9+OHvaawWiGnKo7VwmVvNLb7GL9M9wjdeCQXDLUazL/Ppbf8MnQH+B2zFvk4ArFa65PMiu75jazQ6ChLAGetVawH0DanZav6Msw9d2M2YI8vtl6Is+UdkBVTF8CQptWNuoRGjNYp0gbOtNujx5Ts5KCtYc/DZr9bmoqfVqFtHIHOCrkQzVucvEELwU0VFjvS6/oU5OXUxZpD/TBRI9xrI7ZJcAao/qzHRUDuTGf0UywZS3d9TxmYaLNV8cW15df7hXTvevgkBCWoyTwFmlV+qclPp1xnJSUG2pi+HqCz4i0hO52u8UjnGE9PVykKrswouv4RS/3g50XzB+ucMa9CI2vhtQP7B6s50kTscsoxk/0bjDyJbrYi/Ravs8q4bdhgTCVTM+rAfSReKwfkYktow8K5Kcc=
  template:
    metadata:
      name: memos
      namespace: memos
    type: Opaque
